config {
    type: "table",
    database: constants.pj_raw,
    name: "raw__information_schema__jobs_by_folder",
    description: "This table contains information about the jobs ran in the folder"
}

SELECT
  "INFORMATION_SCHEMA" AS _meta_source_name,
  "JOBS_BY_USER" AS _meta_table_name,
  job_id AS _meta_pk,
  CURRENT_TIMESTAMP() AS _meta_ts_extraction,
  creation_time AS _meta_ts_source,
  *
FROM
  ${ref("JOBS_BY_USER")}
